name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Output Project Name
      id: project_name
      run: |
        export NAME="${GITHUB_REPOSITORY#*/}"
        echo "name=${NAME}" >> $GITHUB_OUTPUT

    - name: Display Project Name
      run: |
        echo "Building Project '${{ steps.project_name.outputs.name }}'"

    - name: Install Lua and LuaRocks
      run: |
        sudo apt-get update
        sudo apt-get install -y liblua5.1-0-dev lua5.1 luarocks

    - name: Install Lua Packages
      run: |
        luarocks install --local yuescript
        luarocks make --local --dev

    - name: Test Project
      run: |
        export PATH="$HOME/.luarocks/bin:$PATH"
        export LUA_PATH="$HOME/.luarocks/share/lua/5.1/?.lua;$HOME/.luarocks/share/lua/5.1/?/init.lua;;"
        export LUA_CPATH="$HOME/.luarocks/lib/lua/5.1/?.so;;"
        yue -e build.yue src -t

    - name: Compile Project
      run: |
        export PATH="$HOME/.luarocks/bin:$PATH"
        export LUA_PATH="$HOME/.luarocks/share/lua/5.1/?.lua;$HOME/.luarocks/share/lua/5.1/?/init.lua;;"
        export LUA_CPATH="$HOME/.luarocks/lib/lua/5.1/?.so;;"
        yue -e build.yue src -d -y

    - name: Build LÖVE applications
      uses: nhartland/love-build@master
      with:
        app_name: ${{ steps.project_name.outputs.name }}
        love_version: '11.4'

    - name: Upload built applications
      uses: actions/upload-artifact@v3
      with:
        name: built-applications
        path: 'release'